# Generated by Django 3.0.7 on 2020-07-05 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Viga',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('b', models.DecimalField(decimal_places=2, max_digits=5)),
                ('h', models.DecimalField(decimal_places=2, max_digits=5)),
                ('d', models.DecimalField(decimal_places=2, max_digits=5)),
                ('d_linha', models.DecimalField(decimal_places=2, max_digits=5)),
                ('limites', models.CharField(max_length=5)),
                ('concreto', models.CharField(max_length=5)),
                ('aco', models.CharField(max_length=5)),
                ('diagrama', models.CharField(max_length=30)),
                ('esforco', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
