# Generated by Django 3.0.8 on 2020-07-08 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vigas', '0002_remove_viga_diagrama'),
    ]

    operations = [
        migrations.AddField(
            model_name='viga',
            name='gama_f',
            field=models.DecimalField(decimal_places=1, default=1.4, max_digits=2),
        ),
    ]
