# Generated by Django 3.0.8 on 2020-07-08 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vigas', '0003_viga_gama_f'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viga',
            name='gama_f',
            field=models.DecimalField(decimal_places=1, max_digits=2),
        ),
    ]
